openapi: 3.0.0
info:
  title: Auth Service
  version: 1.0.0
  description: Микросервис аутентификации
servers:
  - url: http://localhost:8081
    description: Auth Service

paths:
  /api/auth/register:
    post:
      summary: Регистрация клиента
      requestBody: RegisterRequest
      responses:
        '200': AuthResponse
  /api/auth/register/admin:
    post:
      summary: Регистрация админа
      headers: Authorization
      requestBody: RegisterRequest
      responses:
        '200': AuthResponse
  /api/auth/register/manager:
    post:
      summary: Регистрация менеджера
      headers: Authorization
      requestBody: RegisterRequest
      responses:
        '200': AuthResponse
  /api/auth/register/courier:
    post:
      summary: Регистрация курьера
      headers: Authorization
      requestBody: RegisterCourierRequest
      responses:
        '200': string
  /api/auth/login:
    post:
      summary: Вход в систему
      requestBody: AuthRequest
      responses:
        '200': AuthResponse
  /api/auth/validate:
    post:
      summary: Проверка токена
      headers: Authorization
      responses:
        '200': TokenValidationResponse