openapi: 3.0.0
info:
  title: Auth Service API
  version: 1.1.0
  description: Микросервис аутентификации и управления ролями
servers:
  - url: http://localhost:8081
paths:
  /api/auth/register:
    post:
      summary: Регистрация пользователя
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '200':
          description: Успешная регистрация
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'

  /api/auth/register/admin:
    post:
      summary: Регистрация администратора
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '200':
          description: Успешная регистрация администратора
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'

  /api/auth/register/manager:
    post:
      summary: Регистрация менеджера ресторана
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '200':
          description: Успешная регистрация менеджера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'

  /api/auth/login:
    post:
      summary: Вход в систему
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        '200':
          description: Успешный вход
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'

  /api/auth/validate:
    post:
      summary: Проверка токена
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            example: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
      responses:
        '200':
          description: Результат валидации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenValidationResponse'

components:
  schemas:
    AuthRequest:
      type: object
      properties:
        login:
          type: string
        password:
          type: string

    RegisterRequest:
      type: object
      properties:
        login:
          type: string
        password:
          type: string
        email:
          type: string

    AuthResponse:
      type: object
      properties:
        userId:
          type: string
        accessToken:
          type: string
        tokenType:
          type: string
        role:
          type: string

    TokenValidationResponse:
      type: object
      properties:
        valid:
          type: boolean
        userId:
          type: string
        login:
          type: string
        role:
          type: string
