openapi: 3.0.0
info:
  title: Catalog Service
  version: 1.0.0
  description: Микросервис каталога
servers:
  - url: http://localhost:8084
    description: Catalog Service

paths:
  /api/catalog/menu-items:
    get:
      summary: Все блюда
      responses:
        '200': List[CatalogMenuItemDTO]
  /api/catalog/restaurants:
    get:
      summary: Все рестораны
      responses:
        '200': List[CatalogRestaurantDTO]
  /api/catalog/restaurants/{restaurantId}:
    get:
      summary: Конкретный ресторан
      parameters: restaurantId
      responses:
        '200': CatalogRestaurantDTO
  /api/catalog/restaurants/{restaurantId}/menu-items:
    get:
      summary: Меню ресторана
      parameters: restaurantId
      responses:
        '200': List[CatalogMenuItemDTO]
  /api/catalog/internal/sync:
    post:
      summary: Синхронизация каталога
      requestBody: UpdateCatalogRequest
      responses:
        '200': void