openapi: 3.0.0
info:
  title: Courier Service
  version: 1.0.0
  description: Микросервис курьеров
servers:
  - url: http://localhost:8086
    description: Courier Service

paths:
  /api/courier/assignments:
    get:
      summary: Задания курьера
      headers: X-User-Id
      responses:
        '200': List[DeliveryAssignment]
  /api/courier/assignments/{assignmentId}/status:
    put:
      summary: Обновить статус доставки
      headers: X-User-Id
      parameters: assignmentId
      requestBody: UpdateDeliveryStatusRequest
      responses:
        '200': DeliveryAssignment
  /api/courier/internal/orders/{orderId}/assign:
    post:
      summary: Назначить заказ курьеру
      parameters: orderId
      requestBody: AssignOrderRequest
      responses:
        '201': DeliveryAssignment
  /api/courier/internal/create-courier:
    post:
      summary: Создать курьера
      requestBody: CreateCourierRequest
      responses:
        '201': Courier