openapi: 3.0.0
info:
  title: Orders Service
  version: 1.0.0
  description: Микросервис заказов
servers:
  - url: http://localhost:8085
    description: Orders Service

paths:
  /api/orders:
    post:
      summary: Создать заказ
      headers: X-User-Id
      requestBody: CreateOrderRequest
      responses:
        '201': Order
    get:
      summary: Мои заказы
      headers: X-User-Id
      responses:
        '200': List[Order]
  /api/orders/{orderId}:
    get:
      summary: Получить заказ
      headers: X-User-Id
      parameters: orderId
      responses:
        '200': Order
  /api/orders/{orderId}/status:
    put:
      summary: Обновить статус заказа
      headers: X-User-Role
      parameters: orderId
      requestBody: UpdateOrderStatusRequest
      responses:
        '200': Order
  /api/orders/restaurant/{restaurantId}:
    get:
      summary: Заказы ресторана
      headers: X-User-Role
      parameters: restaurantId
      responses:
        '200': List[Order]
  /api/orders/internal/{orderId}:
    get:
      summary: Получить заказ (внутренний)
      parameters: orderId
      responses:
        '200': Order