openapi: 3.0.0
info:
  title: Restaurant Service
  version: 1.0.0
  description: Микросервис ресторанов
servers:
  - url: http://localhost:8083
    description: Restaurant Service

paths:
  /api/management/restaurants:
    post:
      summary: Создать ресторан
      headers: X-User-Role
      requestBody: CreateRestaurantRequest
      responses:
        '201': Restaurant
    get:
      summary: Мои рестораны
      headers: X-User-Id
      responses:
        '200': List[Restaurant]
  /api/management/restaurants/{restaurantId}:
    put:
      summary: Обновить ресторан
      headers: X-User-Id
      parameters: restaurantId
      requestBody: UpdateRestaurantRequest
      responses:
        '200': Restaurant
  /api/management/restaurants/{restaurantId}/menu-items:
    post:
      summary: Добавить блюдо
      headers: X-User-Id
      parameters: restaurantId
      requestBody: CreateMenuItemRequest
      responses:
        '201': MenuItem
    get:
      summary: Получить меню
      headers: X-User-Id
      parameters: restaurantId
      responses:
        '200': List[MenuItem]
  /api/management/restaurants/{restaurantId}/menu-items/{itemId}:
    put:
      summary: Обновить блюдо
      headers: X-User-Id
      parameters: restaurantId, itemId
      requestBody: UpdateMenuItemRequest
      responses:
        '200': MenuItem
    delete:
      summary: Удалить блюдо
      headers: X-User-Id
      parameters: restaurantId, itemId
      responses:
        '200': void