openapi: 3.0.0
info:
  title: User Service
  version: 1.0.0
  description: Микросервис пользователей
servers:
  - url: http://localhost:8082
    description: User Service

paths:
  /api/users/me:
    get:
      summary: Мой профиль
      headers: X-User-Id
      responses:
        '200': UserProfile
    put:
      summary: Обновить профиль
      headers: X-User-Id
      requestBody: UpdateProfileRequest
      responses:
        '200': UserProfile
  /api/users/me/addresses:
    get:
      summary: Мои адреса
      headers: X-User-Id
      responses:
        '200': List[string]
    post:
      summary: Добавить адрес
      headers: X-User-Id
      requestBody: AddAddressRequest
      responses:
        '200': UserProfile
  /api/users/create:
    post:
      summary: Создать профиль
      requestBody: CreateUserRequest
      responses:
        '200': void