server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: order_user
    password: order_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

services:
  user:
    url: http://localhost:8082
  restaurant:
    url: http://localhost:8083
  catalog:
    url: http://localhost:8084
  courier:
    url: http://localhost:8086

logging:
  level:
    com.delivery.order: DEBUG
