server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/courier_db
    username: courier_user
    password: courier_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

services:
  user:
    url: http://localhost:8082
  order:
    url: http://localhost:8085

logging:
  level:
    com.delivery.courier: DEBUG